name: expense_buddy
description: A simple expense tracking app built with Flutter
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fl_chart: ^1.1.0
  flutter_slidable: ^4.0.1
  intl: ^0.20.2
  uuid: ^4.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
